spring.application.name=TaskZen API
# ===============================
# PostgreSQL Configuration
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Set default schema
spring.jpa.properties.hibernate.default_schema=taskzen

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# fallback to validate if env not set
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.properties.hibernate.format_sql=true
